#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('env')

stndir=os.environ['MU2E_BASE_RELEASE']+"/Stntuple"
if (os.path.isdir(stndir)):
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
    rootlibs = env['ROOTLIBS'];
    if (not ("EG" in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"EG");

    Import('stntuple_helper')

    debug = 0;
    helper = stntuple_helper(env,debug=debug);
    
    helper.handle_dictionaries();
    
    skip_list = []
    libs      = [ 'Stntuple_val', 'Stntuple_alg', 'Stntuple_loop',
                  'Stntuple_obj', 'Stntuple_geom', 'Stntuple_base',
                  'mu2e_Mu2eUtilities',
                  'fhiclcpp',
                  'cetlib',
                  'xerces-c',
                  rootlibs
                ]
    
    list_of_cc_files = Glob('*.cc',strings=True);
    helper.build_libs(list_of_cc_files,skip_list,libs);
    
    # print "tmpdir:"+env['TMP_LIB_DIR']
