#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os,copy
Import('muminus_eplus_env')
Import('stntuple_helper')

def local_build():
    local_env = muminus_eplus_env.Clone();
    rootlibs  = local_env['ROOTLIBS'];

    debug = 0;
    helper = stntuple_helper(local_env,debug=debug);

    helper.handle_dictionaries();
    
    skip_list = []
    
    stntuple_libs = [ 'Stntuple_val', 'Stntuple_alg', 'Stntuple_loop',
                      'Stntuple_obj', 'Stntuple_geom', 'Stntuple_base'
                  ];
    libs      = stntuple_libs + [
                  'mu2e_Mu2eUtilities',
                  'fhiclcpp',
                  'cetlib',
                  'xerces-c',
                  rootlibs
                ]
    
    list_of_cc_files = Glob('*.cc',strings=True);
    helper.build_libs(list_of_cc_files,skip_list,libs);

#-------------------------------------------------------- END
local_build()
# print "tmpdir:"+env['TMP_LIB_DIR']
