#!/bin/bash

dir=include

# echo pwd  `pwd`

#------------------------------------------------------------------------------
# 'muminus_eplus' and its subpackages, excluding Stntuple
#------------------------------------------------------------------------------
if [ -d $MU2E_BASE_RELEASE/Stntuple ] ; then 
    
    if [ ! -d ../$dir/muminus_eplus ] ; then mkdir -p ../$dir/muminus_eplus ; fi
    
    for d in ana ; do
	if [ ! -e ../$dir/muminus_eplus/$d ] ; then 
	    echo `pwd`$0 : creating symbolic link ../$dir/muminus_eplus/$d
	    ln -s ../../muminus_eplus/$d/$d ../$dir/muminus_eplus/$d
	fi
    done
    
fi
#------------------------------------------------------------------------------
# muminus_eplus/Stntuple and its subpackages
#------------------------------------------------------------------------------
# if [ ! -d ../$dir/Stntuple ] ; then mkdir -p ../$dir/Stntuple ; fi
# 
# # for d in alg base gui loop mod obj val ; do
# for d in alg base loop mod obj val ; do
#     if [ ! -e ../$dir/Stntuple/$d ] ; then 
# 	echo `pwd`$0 : creating symbolic link ../$dir/Stntuple/$d
# 	ln -s ../../muminus_eplus/Stntuple/$d/$d ../$dir/Stntuple/$d
#     fi
# done
