#!/bin/bash
#------------------------------------------------------------------------------
# 'muminus_eplus' and its subpackages (assume Stntuple is around)
#------------------------------------------------------------------------------
pkg=muminus_eplus

base=$MU2E_SATELLITE_RELEASE
if [ ".$base" == "." ] ; then 
   base=$MU2E_BASE_RELEASE
fi

# echo building $pkg, pwd  `pwd`
if [ ! -d $base/include/$pkg ] ; then mkdir -p $base/include/$pkg ; fi

for d in ana obj ; do
    if [ ! -e $base/include/$pkg/$d ] ; then 
	echo `pwd`/$0 : creating symbolic link $base/include/$pkg/$d
	ln -s ../../$pkg/$d/$d $base/include/$pkg/$d
    fi
done
