#!/bin/bash
#------------------------------------------------------------------------------
# 'muminus_eplus' and its subpackages (assume Stntuple is around)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# make sure Stntuple build_config is executed
#------------------------------------------------------------------------------
pushd ../Stntuple ; scripts/build_config ; popd ;

pkg=muminus_eplus

base=$MUSE_WORK_DIR/build
    dir=$base/include
pkg_dir=$MUSE_WORK_DIR/$pkg

# echo building $pkg, pwd  `pwd`
if [ ! -d $base/include/$pkg ] ; then mkdir -p $base/include/$pkg ; fi

for d in ana obj ; do
    if [ ! -e $dir/$pkg/$d ] ; then 
	echo `pwd`/$0 : creating symbolic link $dir/$pkg/$d
	ln -s $pkg_dir/$d/$d $dir/$pkg/$d
    fi
done
